# Funding platforms for PPM (Python Package Manager)
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [DrQedwards]
buy_me_a_coffee: drqedwards
custom: ["https://pypi.org/project/ppm/"]
